import "./globals.css";
import { use } from "react";
import parseFile from "../api/ParseLog";

export const metadata = {
  title: "Log Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  use(parseFile);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
